version: '3.9'
services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "9090:8080"
    networks:
      - docandzipnetwork
  postgres:
    image: postgres:9.6
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=DocAndZip
    ports:
      - "5432:5432"
    volumes:
      - ./data/local:/var/lib/postgresql/data
    networks:
      - docandzipnetwork
networks:
  docandzipnetwork: